### ISSUE TITLE
WTF IS THE TOKEN FOR?!?!?!

### ISSUE THREAD

**Issue by jdhydra** [deansheather/discord-selfbot#2]
Plz halp what is a user token for?!!?!?!

**Comment by jdhydra** [comment]
I cant find ANYTHING for the "token" in credentials.json

**Comment by deansheather** [comment]
?

**Comment by Zeludon** [comment]
I think its a type of rare cheese, would explain why discord wants so many of them

**Comment by jdhydra** [comment]
I think it is too ( ͡° ͜ʖ ͡°)
